Repository fcpkata/pricing, pull requests merged in 2020-08, with the labels that each got.

#2 Cicd config
  .gitignore
  Dockerfile
  OWNERS
  OWNERS_ALIASES
  build.gradle
  charts/pricing/values.yaml
  gradlew
  src/main/java/com/kata/priceservice/controller/PricingController.java
  src/main/resources/application.properties
  src/test/java/com/kata/priceservice/controller/PricingControllerAcceptanceSpec.java
Labels: approved, size/M

#1 Added new end point for fetching Shipping Price
  build.gradle
  charts/inventory/.helmignore
  charts/inventory/Chart.yaml
  charts/inventory/Makefile
  charts/inventory/README.md
  charts/inventory/templates/NOTES.txt
  charts/inventory/templates/_helpers.tpl
  charts/inventory/templates/canary.yaml
  charts/inventory/templates/deployment.yaml
  charts/inventory/templates/hpa.yaml
  charts/inventory/templates/ingress.yaml
  charts/inventory/templates/ksvc.yaml
  charts/inventory/templates/service.yaml
  charts/inventory/values.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  deploy/Dockerfile
  deploy/pricing-deployment.yaml
  jenkins-x.yml
  settings.gradle
  src/main/java/com/kata/priceservice/PricingServiceApplication.java
  src/main/java/com/kata/priceservice/controller/PricingController.java
  src/main/java/com/kata/priceservice/controller/advice/ControllerExceptionHandler.java
  src/main/java/com/kata/priceservice/exception/CityNotFoundException.java
  src/main/java/com/kata/priceservice/exception/InvalidCityException.java
  src/main/java/com/kata/priceservice/service/DomesticShippingChargeCalculator.java
  src/main/java/com/kata/priceservice/service/InternationalShippingChargeCalculator.java
  src/main/java/com/kata/priceservice/service/LocalShippingChargeCalculator.java
  src/main/java/com/kata/priceservice/service/MockShippingChargesService.java
  src/main/java/com/kata/priceservice/service/ShippingChargeCalculator.java
  src/main/java/com/kata/priceservice/service/ShippingChargesService.java
  src/main/java/com/kata/priceservice/service/ShippingPriceCordinator.java
  src/main/java/model/City.java
  src/main/java/model/Price.java
  src/test/java/com/kata/priceservice/controller/PricingControllerAcceptanceSpec.java
  src/test/java/com/kata/priceservice/controller/PricingControllerSpec.java
  src/test/java/com/kata/priceservice/service/ShippingPriceCordinatorTest.java
  src/test/java/library/CurrencySpec.java
Labels: approved, size/XL

#3 Refactor existing design to accomodate additional shipping price calc…
  src/main/java/com/kata/priceservice/controller/PricingController.java
  src/main/java/com/kata/priceservice/model/City.java
  src/main/java/com/kata/priceservice/model/Price.java
  src/main/java/com/kata/priceservice/model/ShippingPriceRequest.java
  src/main/java/com/kata/priceservice/service/DefaultShippingPriceCalculator.java
  src/main/java/com/kata/priceservice/service/DomesticShippingChargeCalculator.java
  src/main/java/com/kata/priceservice/service/DomesticShippingPriceCalculator.java
  src/main/java/com/kata/priceservice/service/InternationalShippingChargeCalculator.java
  src/main/java/com/kata/priceservice/service/InternationalShippingPriceCalculator.java
  src/main/java/com/kata/priceservice/service/LocalShippingChargeCalculator.java
  src/main/java/com/kata/priceservice/service/LocalShippingPriceCalculator.java
  src/main/java/com/kata/priceservice/service/LocationBasedShippingPriceCalculator.java
  src/main/java/com/kata/priceservice/service/MockShippingChargesService.java
  src/main/java/com/kata/priceservice/service/ShippingChargeCalculator.java
  src/main/java/com/kata/priceservice/service/ShippingPriceCalculator.java
  src/main/java/com/kata/priceservice/service/ShippingPriceCoordindator.java
  src/main/java/com/kata/priceservice/service/ShippingPriceCordinator.java
  src/test/java/com/kata/priceservice/controller/PricingControllerSpec.java
  src/test/java/com/kata/priceservice/service/DomesticShippingPriceCalculatorTest.java
  src/test/java/com/kata/priceservice/service/InternationalShippingPriceCalculatorTest.java
  src/test/java/com/kata/priceservice/service/LocalShippingPriceCalculatorTest.java
  src/test/java/com/kata/priceservice/service/LocationBasedShippingPriceCalculatorTest.java
  src/test/java/com/kata/priceservice/service/ShippingPriceCordinatorTest.java
Labels: approved, size/XL

#4 Volume based calculator
  src/main/java/com/kata/priceservice/controller/PricingController.java
  src/main/java/com/kata/priceservice/controller/advice/ControllerExceptionHandler.java
  src/main/java/com/kata/priceservice/exception/InvalidVolumeException.java
  src/main/java/com/kata/priceservice/model/ShippingPriceRequest.java
  src/main/java/com/kata/priceservice/service/ShippingPriceCoordindator.java
  src/main/java/com/kata/priceservice/service/VolumeBasedShippingPriceCalculator.java
  src/test/java/com/kata/priceservice/controller/PricingControllerAcceptanceSpec.java
  src/test/java/com/kata/priceservice/controller/PricingControllerSpec.java
  src/test/java/com/kata/priceservice/service/VolumeBasedShippingPriceCalculatorTest.java
Labels: approved, size/L

#6 Shiping price calculation based on weight
  src/main/java/com/kata/priceservice/controller/PricingController.java
  src/main/java/com/kata/priceservice/controller/advice/ControllerExceptionHandler.java
  src/main/java/com/kata/priceservice/exception/InvalidWeightException.java
  src/main/java/com/kata/priceservice/model/ShippingPriceRequest.java
  src/main/java/com/kata/priceservice/service/ShippingPriceCoordindator.java
  src/main/java/com/kata/priceservice/service/WeightBasedShippingPriceCalculator.java
  src/test/java/com/kata/priceservice/controller/PricingControllerAcceptanceSpec.java
  src/test/java/com/kata/priceservice/controller/PricingControllerSpec.java
  src/test/java/com/kata/priceservice/service/WeightBasedShippingPriceCalculatorTest.java
Labels: approved, lgtm, size/L
